### ISSUE TITLE
Hotel Listing (CONTINUE)

### ISSUE THREAD

**Issue by phuoctaiismee** [phuoctaiismee/teknix-lalala#31]
https://preview.themeforest.net/item/bookinga-multipurpose-vue-booking-and-directory-template/full_screen_preview/53742271
![Image](https://github.com/user-attachments/assets/1dae8f5b-f878-48d1-9731-92424cfe828d)
![Image](https://github.com/user-attachments/assets/9fac7992-1b6d-42d6-8fbb-6cbb9c83ef34)

**Comment by hientt1803** [comment]
continue now. Waiting to integrate map for third variant
